experiences/urls.py
from django.urls import path

from .views import (
    ExperienceCreateView,
    ExperienceUpdateView,
    ExperienceDescriptionUpdateView,
)

app_name = "experiences"

urlpatterns = [
    path("<int:pk>/create/", ExperienceCreateView.as_view(), name="create_experience"),
    path("<int:pk>/update/", ExperienceUpdateView.as_view(), name="update_experience"),
    path(
        "<int:pk>/update-description/",
        ExperienceDescriptionUpdateView.as_view(),
        name="update_experience_description",
    ),
]

hobby/urls.py
from django.urls import path

from .views import HobbyCreateView, HobbyUpdateView, HobbyListView

app_name = "hobby"

urlpatterns = [
    path("<int:pk>/create/", HobbyCreateView.as_view(), name="create_hobby"),
    path("<int:pk>/update/", HobbyUpdateView.as_view(), name="update_hobby"),
    path("", HobbyListView.as_view(), name="hobbies_list"),
]

resume_builder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("personals/", include("personals.urls", namespace="personals")),
    path("skills/", include("skills.urls", namespace="skills")),
    path("hobby/", include("hobby.urls", namespace="hobby")),
    path("schools/", include("schools.urls", namespace="schools")),
    path("experiences/", include("experiences.urls", namespace="experiences")),
    path("", include("resumes.urls", namespace="resumes")),
    path("", include("django.contrib.auth.urls")),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="reset_password_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="reset_password_complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resumes/urls.py
from django.urls import path

from .views import (
    ResumeCreateView,
    ResumeUpdateView,
    ResumeListView,
    ResumeDetailView,
    ResumeDeleteView,
    HomeView,
)

app_name = "resumes"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("resumes/", ResumeListView.as_view(), name="resumes"),
    path("create/", ResumeCreateView.as_view(), name="create_resume"),
    path("<int:pk>/update", ResumeUpdateView.as_view(), name="update_resume"),
    path("<int:pk>/", ResumeDetailView.as_view(), name="resume"),
    path("<int:pk>/delete", ResumeDeleteView.as_view(), name="delete_resume"),
]

experiences/models.py
from django.db import models

from resumes.models import Resume


class Experience(models.Model):
    resume = models.ForeignKey(
        Resume, on_delete=models.CASCADE, related_name="experience"
    )
    company = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    position = models.CharField(max_length=200)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return f"{str(self.company)}"


class ExperienceDescription(models.Model):
    experience = models.ForeignKey(
        Experience, on_delete=models.CASCADE, related_name="experience_description"
    )
    description = models.TextField()

    def __str__(self):
        return f"{str(self.description)}"

experiences/forms.py
from django import forms
from django.forms import modelformset_factory

from .models import Experience, ExperienceDescription


class ExperienceForms(forms.ModelForm):
    class Meta:
        model = Experience
        fields = ["company", "city", "position", "start_date", "end_date"]

    company = forms.CharField(
        label="Company Name", widget=forms.TextInput(attrs={"placeholder": "Google"})
    )
    city = forms.CharField(
        label="City", widget=forms.TextInput(attrs={"placeholder": "Mountain View"})
    )
    position = forms.CharField(
        label="Position",
        widget=forms.TextInput(attrs={"placeholder": "Junior Backend Developer"}),
    )
    start_date = forms.DateField(
        label="Start date",
        widget=forms.DateInput(
            attrs={
                "placeholder": "01.10.2015",
                "type": "text",
                "onfocus": "(this.type='date')",
            }
        ),
    )
    end_date = forms.DateField(
        label="End date",
        widget=forms.DateInput(
            attrs={
                "placeholder": "15.07.2018",
                "type": "text",
                "onfocus": "(this.type='date')",
            }
        ),
    )


ExperienceFormSet = modelformset_factory(
    Experience,
    form=ExperienceForms,
    fields=("company", "city", "position", "start_date", "end_date"),
    extra=1,
)


class ExperienceDescriptionForms(forms.ModelForm):
    class Meta:
        model = ExperienceDescription
        fields = ["description"]

    description = forms.CharField(
        label="Job description",
        widget=forms.Textarea(attrs={"placeholder": "Describe your experience"}),
    )


ExperienceDescriptionFormSet = modelformset_factory(
    ExperienceDescription,
    form=ExperienceDescriptionForms,
    fields=("description",),
    extra=1,
)

experiences/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView

from resumes.models import Resume
from .forms import ExperienceForms, ExperienceDescriptionFormSet, ExperienceFormSet
from .models import Experience, ExperienceDescription


class ExperienceCreateView(LoginRequiredMixin, CreateView):
    template_name = "experience_form.html"
    success_message = "Experience was created successfully"

    def get(self, request, *args, **kwargs):
        form = ExperienceForms()
        formset = ExperienceDescriptionFormSet(
            queryset=ExperienceDescription.objects.none()
        )
        return self.render_to_response({"form": form, "formset": formset})

    def post(self, request, *args, **kwargs):
        form = ExperienceForms(data=self.request.POST)
        formset = ExperienceDescriptionFormSet(data=self.request.POST)
        if form.is_valid() and formset.is_valid():
            instance = form.save(commit=False)
            resume_id = self.kwargs["pk"]
            instance.resume = Resume.objects.get(id=resume_id)
            instance.save()
            description_instances = formset.save(commit=False)
            for description_instance in description_instances:
                resume_id = self.kwargs["pk"]
                description_instance.experience = Experience.objects.filter(
                    resume_id=resume_id
                ).last()
                description_instance.save()
            form.save()
            formset.save()
            if "create_exp" in self.request.POST:
                return redirect(
                    reverse_lazy(
                        "experiences:create_experience",
                        kwargs={"pk": self.kwargs["pk"]},
                    )
                )
            else:
                return redirect(
                    reverse_lazy(
                        "skills:create_skill", kwargs={"pk": self.kwargs["pk"]}
                    )
                )
        return self.render_to_response({"form": form, "formset": formset})


class ExperienceUpdateView(LoginRequiredMixin, UpdateView):
    model = Experience
    template_name = "experience_update.html"
    success_message = "Experience was updated successfully"

    def get(self, *args, **kwargs):
        formset = ExperienceFormSet(
            queryset=Experience.objects.filter(resume_id=self.kwargs["pk"])
        )
        return self.render_to_response({"formset": formset})

    def post(self, request, *args, **kwargs):
        formset = ExperienceFormSet(data=self.request.POST)

        if formset.is_valid():
            if "save" in self.request.POST:
                formset.save()
                messages.success(self.request, self.success_message)
                return redirect(reverse_lazy("resumes:resumes"))
        return self.render_to_response({"formset": formset})


class ExperienceDescriptionUpdateView(LoginRequiredMixin, UpdateView):
    model = ExperienceDescription
    template_name = "experience_description_update.html"
    success_message = "Experience description was updated successfully"

    def get(self, *args, **kwargs):
        formset = ExperienceDescriptionFormSet(
            queryset=ExperienceDescription.objects.filter(
                experience_id=self.kwargs["pk"]
            )
        )

        return self.render_to_response({"formset": formset})

    def post(self, request, *args, **kwargs):
        formset = ExperienceDescriptionFormSet(data=self.request.POST)

        if formset.is_valid():
            formset.save()
            messages.success(self.request, self.success_message)
            return redirect(reverse_lazy("resumes:resumes"))
        return self.render_to_response({"formset": formset})

experiences/templates/experiences/experience_description_update.html
{% extends 'base.html' %}

{% block title %}Update experience{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h2 class="text-center text-uppercase">Update experience description</h2>

    <div class="col-md-10 offset-md-1 my-4">
        <a href="{{request.META.HTTP_REFERER|escape}}"><i class="bi bi-arrow-left-circle mt-4 ms-3"></i></a>
        <form method="POST" class="form-group mt-4" id="form-container">
            <ul class="list-group list-group-flush">
                {% csrf_token %}
                {{formset.management_form|crispy}}
                {% for form in formset|slice:":-1"  %}
                    <li class="list-group-item">
                        {{ form|crispy }}
                    </li>
                {% endfor %}
            </ul>
            <button type="submit" name="save" class="btn btn-success float-end me-3">Update</button>
        </form>
    </div>
{% endblock %}

experiences/templates/experiences/experience_form.html
{% extends 'base.html' %}

{% block title %}Add experience{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h2 class="text-center text-uppercase">Add a new experience</h2>

    <div class="col-md-10 offset-md-1 my-4">
        <div class="progress my-4 mx-3">
            <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 66.8%" aria-valuenow="66.8" aria-valuemin="0" aria-valuemax="100"></div>
        </div>

        <form method="POST" class="form-group mt-4">
            <div class="div-container">
                {% csrf_token %}
                <ul class="list-group list-group-flush" id="ul-container">
                    <li class="list-group-item experience-form">
                        {{ form|crispy }}
                    </li>
                    {{ formset.management_form }}
                    {% for form_description in formset %}
                        <div class="experienceDescription-form mx-3">
                            {{ form_description|crispy }}
                        </div>
                    {% endfor %}
                </ul>
            </div>
            <div class="row my-3 ms-3">
                <button id="add-formDescription" type="button" name="add" class="btn btn-info float-start col-auto">Add Another Job Description</button>
            </div>
            <button type="submit" name="create_exp" class="btn btn-primary float-start ms-3">Create Another Experience</button>
            <button type="submit" name="save" class="btn btn-success float-end me-3">Go to the skills section</button>
        </form>
    </div>

    <script>
        let container = document.querySelector('#ul-container')
        let totalForms = document.querySelector('#id_form-TOTAL_FORMS')

        totalForms.setAttribute('value', 2)

        let experienceDescriptionForm = document.querySelectorAll('.experienceDescription-form')
        let descriptionContainer = document.querySelector('#div-container')
        let addDescriptionButton = document.querySelector('#add-formDescription')
        let formDescriptionNum = document.getElementsByClassName('textarea').length - 1

        addDescriptionButton.addEventListener('click', addDescriptionForm)

        function addDescriptionForm(e) {
            e.preventDefault()

            let newDescriptionForm =  experienceDescriptionForm[0].cloneNode(true)
            let formRegex = RegExp(`form-(\\d){1}-`,'g')

            formDescriptionNum++

            newDescriptionForm.innerHTML = newDescriptionForm.innerHTML.replace(formRegex, `form-${formDescriptionNum}-`)
            container.appendChild(newDescriptionForm)

            totalForms.setAttribute('value', `${parseInt(totalForms.value, 10) + 1}`)
        }
    </script>
{% endblock %}

experiences/templates/experiences/experience_update.html
{% extends 'base.html' %}

{% block title %}Update experience{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h2 class="text-center text-uppercase">Update experience</h2>

    <div class="col-md-10 offset-md-1 my-4">
        <a href="{% url 'resumes:resumes' %}"><i class="bi bi-arrow-left-circle mt-4 ms-3"></i></a>
        <form method="POST" class="form-group mt-4" id="form-container">
            <ul class="list-group list-group-flush">
                {% csrf_token %}
                {{ formset.management_form|crispy}}
                {% for form in formset|slice:":-1"  %}
                    <li class="list-group-item">
                        {{ form|crispy }}
                        <button type="submit" name="description" formmethod='get' formaction="{% url 'experiences:update_experience_description' form.instance.id %}" class="btn btn-info start">Update Job Description</button>
                    </li>
                {% endfor %}
            </ul>
            <button type="submit" name="save" class="btn btn-success float-end me-3">Update Experiences</button>
        </form>
    </div>
{% endblock %}