hobby/urls.py
from django.urls import path

from .views import HobbyCreateView, HobbyUpdateView, HobbyListView

app_name = "hobby"

urlpatterns = [
    path("<int:pk>/create/", HobbyCreateView.as_view(), name="create_hobby"),
    path("<int:pk>/update/", HobbyUpdateView.as_view(), name="update_hobby"),
    path("", HobbyListView.as_view(), name="hobbies_list"),
]

resume_builder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("personals/", include("personals.urls", namespace="personals")),
    path("skills/", include("skills.urls", namespace="skills")),
    path("hobby/", include("hobby.urls", namespace="hobby")),
    path("schools/", include("schools.urls", namespace="schools")),
    path("experiences/", include("experiences.urls", namespace="experiences")),
    path("", include("resumes.urls", namespace="resumes")),
    path("", include("django.contrib.auth.urls")),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="reset_password_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="reset_password_complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resumes/urls.py
from django.urls import path

from .views import (
    ResumeCreateView,
    ResumeUpdateView,
    ResumeListView,
    ResumeDetailView,
    ResumeDeleteView,
    HomeView,
)

app_name = "resumes"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("resumes/", ResumeListView.as_view(), name="resumes"),
    path("create/", ResumeCreateView.as_view(), name="create_resume"),
    path("<int:pk>/update", ResumeUpdateView.as_view(), name="update_resume"),
    path("<int:pk>/", ResumeDetailView.as_view(), name="resume"),
    path("<int:pk>/delete", ResumeDeleteView.as_view(), name="delete_resume"),
]

users/urls.py
from django.urls import path

from .views import sign_up, login_view, logout_view

app_name = "users"

urlpatterns = [
    path("sign-up/", sign_up, name="sign_up"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
]

templates/base.html
{% load static %}
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/bootstrap.min.css' %}"
/>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
        <title>{% block title %}{% endblock %}</title>

        <style>
            a {
                color: #fff;
                text-decoration: none;
            }

            a.badge.rounded-pill.bg-light:hover  {
                color: #fff;
                background-color: #1a1a1a!important;
            }

            a.sign_up, a.reset_password, a.login {
                color: #000;
                text-decoration: underline;
            }

            a.create:hover {
                color: #fff;
                opacity: 0.5;
            }

            button.create:hover {
                opacity: 0.9;
            }

            a.sign_up:hover, a.reset_password:hover, a.login:hover {
                text-decoration: none;
            }

            .bi-arrow-left-circle{
                color:red;
                font-size:35px;
            }

            .bi-arrow-left-circle:hover {
                opacity: 0.4;
            }

            .fa-envelope, .fa-github-square, .fa-linkedin {
                font-size: 25px;
                color: silver;
            }

            .fa-envelope:hover, .fa-github-square:hover, .fa-linkedin:hover {
                color: rgb(248, 249, 250);
            }
            {% block style %}{% endblock %}
        </style>
    </head>
    <body class="d-flex flex-column min-vh-100">
        <div class="wrapper flex-grow-1">
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'resumes:home' %}">RESUME BUILDER</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarColor01">
                        <ul class="navbar-nav me-auto">
                            {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'resumes:create_resume' %}">Resume</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'resumes:resumes' %}">Resume List</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'users:sign_up' %}">Sign Up</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-dismissible alert-{{message.tags}} fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        <p class="mb-0">{{message}}</p>
                    </div>
                {% endfor %}
            {% endif %}

            <div class="container">
                <div class="row">
                    <div class="col-md-10 offset-md-1 my-4">
                        {% block content %}

                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <footer class="footer bg-primary text-light py-4">
            <div class="container">
                <div class="row">
                    <div class="social col-md-12 d-flex justify-content-center pb-1">
                        <span
                        ><a href="mailto: p.romanczuk31@gmail.com"
                        ><i class="fas fa-envelope mx-3"></i></a
                            ></span>
                            <span
                            ><a href="https://github.com/Gamattowicz"
                            ><i class="fab fa-github-square mx-3"></i></a
                                ></span>
                                <span
                                ><a href="https://linkedin.com/in/przemysław-romańczuk"
                                ><i class="fab fa-linkedin mx-3"></i></a
                                    ></span>
                                </div>
                                <div class="copyright col-md-12 d-flex justify-content-center pt-1">
                                    <span>© 2021 Copyright | Designed by Przemysław Romańczuk</span>
                                </div>
                            </div>
                        </div>
                    </footer>

                </body>
            </html>

templates/pagination.html
{% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination pagination-lg justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item active">
                    <a  class="page-link" href="?page={{page_obj.previous_page_number }}">&laquo; Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">&laquo; Previous</a>
                </li>
            {% endif %}
            {% for page in paginator.page_range %}
                {% if page_obj.number == page %}
                    <li class="page-item active">
                        <a class="page-link">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next &raquo;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next &raquo;</a>
                </li>
            {% endif %}
        </ul>
{% endif %}
</nav>

templates/reset_password.html
{% extends 'base.html' %}

{% block title %}Reset password{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h2 class="text-center text-uppercase">Password reset</h2>

    <div class="col-md-8 offset-md-2 my-4">
        <p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>
        <form method="POST" class="form-group" id="form-container">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" name="save" class="btn btn-success float-start">Submit</button>
        </form>
    </div>

{% endblock %}

templates/reset_password_complete.html
{% extends 'base.html' %}

{% block title %}PASSWORD RESET COMPLETE{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h2 class="text-center text-uppercase">Password reset complete</h2>

    <div class="col-md-8 offset-md-2 my-4">
        <p>Your password has been set. You may go ahead and log in now.</p>
        <a href="{% url 'users:login' %}" class="login">Log in</a>
    </div>

{% endblock %}

templates/reset_password_sent.html
{% extends 'base.html' %}

{% block title %}PASSWORD RESET SENT{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h2 class="text-center text-uppercase">Password reset sent</h2>
    <div class="col-md-8 offset-md-2 my-4">
        <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered.
            You should receive them shortly.</p>
        <p>If you don’t receive an email, please make sure you’ve entered the address you registered with,
            and check your spam folder.</p>
    </div>
{% endblock %}