hobby/urls.py
from django.urls import path

from .views import HobbyCreateView, HobbyUpdateView, HobbyListView

app_name = "hobby"

urlpatterns = [
    path("<int:pk>/create/", HobbyCreateView.as_view(), name="create_hobby"),
    path("<int:pk>/update/", HobbyUpdateView.as_view(), name="update_hobby"),
    path("", HobbyListView.as_view(), name="hobbies_list"),
]

personals/urls.py
from django.urls import path

from .views import PersonalCreateView, PersonalUpdateView

app_name = "personals"

urlpatterns = [
    path("<int:pk>/create/", PersonalCreateView.as_view(), name="create_personal"),
    path("<int:pk>/update", PersonalUpdateView.as_view(), name="update_personal"),
]

resume_builder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("personals/", include("personals.urls", namespace="personals")),
    path("skills/", include("skills.urls", namespace="skills")),
    path("hobby/", include("hobby.urls", namespace="hobby")),
    path("schools/", include("schools.urls", namespace="schools")),
    path("experiences/", include("experiences.urls", namespace="experiences")),
    path("", include("resumes.urls", namespace="resumes")),
    path("", include("django.contrib.auth.urls")),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="reset_password_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="reset_password_complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resumes/urls.py
from django.urls import path

from .views import (
    ResumeCreateView,
    ResumeUpdateView,
    ResumeListView,
    ResumeDetailView,
    ResumeDeleteView,
    HomeView,
)

app_name = "resumes"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("resumes/", ResumeListView.as_view(), name="resumes"),
    path("create/", ResumeCreateView.as_view(), name="create_resume"),
    path("<int:pk>/update", ResumeUpdateView.as_view(), name="update_resume"),
    path("<int:pk>/", ResumeDetailView.as_view(), name="resume"),
    path("<int:pk>/delete", ResumeDeleteView.as_view(), name="delete_resume"),
]

schools/urls.py
from django.urls import path

from .views import SchoolCreateView, SchoolUpdateView

app_name = "schools"

urlpatterns = [
    path("<int:pk>/create/", SchoolCreateView.as_view(), name="create_school"),
    path("<int:pk>/update", SchoolUpdateView.as_view(), name="update_school"),
]

skills/urls.py
from django.urls import path

from .views import SkillCreateView, SkillUpdateView, SkillListView

app_name = "skills"

urlpatterns = [
    path("<int:pk>/create/", SkillCreateView.as_view(), name="create_skill"),
    path("<int:pk>/update", SkillUpdateView.as_view(), name="update_skill"),
    path("", SkillListView.as_view(), name="skill_list"),
]

users/urls.py
from django.urls import path

from .views import sign_up, login_view, logout_view

app_name = "users"

urlpatterns = [
    path("sign-up/", sign_up, name="sign_up"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
]

resumes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Resume(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="resume", null=True
    )
    template = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{str(self.template)}"

    def get_absolute_url(self):
        return reverse("personals:create_personal", kwargs={"pk": self.pk})

    class Meta:
        ordering = ["-created"]

resumes/forms.py
from django import forms
from django.utils.safestring import mark_safe

from .models import Resume

TEMPLATES_CHOICES = (
    (
        "1",
        mark_safe(
            '<img src="/images/resume_1_thumbnail.PNG" class="img-fluid d-block w-50 mx-auto" alt="Responsive image">'
        ),
    ),
    (
        "2",
        mark_safe(
            '<img src="/images/resume_2_thumbnail.PNG" class="img-fluid d-block w-50 mx-auto" alt="Responsive image">'
        ),
    ),
    (
        "3",
        mark_safe(
            '<img src="/images/resume_3_thumbnail.PNG" class="img-fluid d-block w-50 mx-auto" alt="Responsive image">'
        ),
    ),
)


class ResumeForms(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ["template"]

    template = forms.ChoiceField(
        label="Choose a template",
        choices=TEMPLATES_CHOICES,
        widget=forms.widgets.RadioSelect,
    )

resumes/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import DeleteView, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from .forms import ResumeForms
from .models import Resume


class ResumeCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Resume
    form_class = ResumeForms
    success_message = "Resume was created successfully"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ResumeCreateView, self).form_valid(form)


class ResumeUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Resume
    form_class = ResumeForms
    success_url = reverse_lazy("resumes:resumes")
    template_name = "resumes/resume_update.html"
    success_message = "Resume template was updated successfully"


class ResumeListView(LoginRequiredMixin, ListView):
    model = Resume
    context_object_name = "resumes"
    paginate_by = 6

    def get_queryset(self):
        queryset = Resume.objects.filter(user=self.request.user)
        return queryset


class ResumeDetailView(LoginRequiredMixin, DetailView):
    model = Resume
    context_object_name = "resume"

    def get_template_names(self):
        object = Resume.objects.get(id=self.kwargs["pk"])
        return f"resume_{object.template}.html"


class ResumeDeleteView(LoginRequiredMixin, DeleteView):
    model = Resume
    context_object_name = "resume"
    success_url = reverse_lazy("resumes:resumes")
    template_name = "resume_delete.html"
    success_message = "Resume deleted"

    def delete(self, request, *args, **kwargs):
        messages.error(self.request, self.success_message)
        return super(ResumeDeleteView, self).delete(request, *args, **kwargs)


class HomeView(TemplateView):
    template_name = "home.html"

resumes/templates/resumes/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block content %}


    <div class="row mb-3 d-flex align-items-center">
        <div class="col-sm-6">
            <h1 class="text-center fw-bold mb-5" style="font-size:55px">Resume Builder</h1>
            <h5 class="text-center mb-5">
                Create your resume quickly and easily by choosing one of the available templates.
            </h5>
            <div class="text-center">
                {% if user.is_authenticated %}
                    <button type="button" class="btn btn-primary btn-lg my-3 create"><a href='{% url "resumes:create_resume" %}' class="create"
                        style="font-size:30px;">Create Resume</a></button>
                {% else %}
                    <button type="button" class="btn btn-primary btn-lg my-3 create"><a href='{% url "users:login" %}' class="create"
                        style="font-size:30px;">Create Resume</a></button>
                {% endif %}
            </div>
        </div>
        <div class="col-sm-6 text-center">
            <img
                src="/images/resume_2_thumbnail.PNG"
                class="img-thumbnail rounded float-start"
            />
        </div>
    </div>
{% endblock %}

resumes/templates/resumes/resume_1.html
{% load static %}
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/bootstrap.css' %}"
/>
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/resume_1_2.min.css' %}"
/>
<script src="{% static 'js/bootstrap.js' %}"></script>

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Resume 1</title>
        <style type="text/css">
            ul.skills {
                list-style-type: none;
                padding-left: 0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-8  p-0 me-2">
                    <div class="p-4">
                        <p class='text-uppercase fs-1 fw-bolder text-dark mb-4'>{{ resume.personal.first_name }} {{ resume.personal.last_name }}</p>

                        <p class='text-uppercase fs-3 fw-bolder text-dark mt-4'>Career overview</p>
                        <p class='text-dark'>{{ resume.personal.description }}</p>

                        <div class="row mt-5 mb-2">
                            <p class='text-uppercase fs-3 fw-bolder text-dark'>Work experience</p>
                        </div>
                        {% for exp in resume.experience.all %}
                            <p class='fs-4 fw-bolder text-dark'>{{ exp.position }}</p>
                            <p class='fs-6 text-dark fst-italic'>{{ exp.company }} - {{ exp.city }} | {{ exp.start_date }} - {{ exp.end_date }}</p>
                            <ul class='text-dark'>
                                {% for exp_description in exp.experience_description.all %}
                                    <li>{{ exp_description.description }}</li>
                                {% endfor %}
                            </ul>
                        {% endfor %}

                        <div class="row mt-5 mb-2">
                            <p class='text-uppercase fs-3 fw-bolder text-dark'>Education</p>
                        </div>
                        {% for school in resume.school.all %}
                            <p class='fs-4 fw-bolder text-dark'>{{ school.name }} - {{ school.city }}</p>
                            <p class='fs-6 text-dark fst-italic'>{{ school.degree }} | {{ school.start_date }} - {{ school.end_date }}</p>
                            <ul class='text-dark'>
                                <li>Masters in Software Engineering</li>
                                <li>Took advanced courses on software architecture and computer science research</li>
                                <li>Participated in enterprise system projects</li>
                            </ul>
                        {% endfor %}

                        <div class="row mt-5 mb-2">
                            <p class='text-uppercase fs-3 fw-bolder text-dark'>Hobby</p>
                        </div>
                        <ul class='text-dark'>
                            {% for hobby in resume.hobby.all %}
                                <li>{{hobby.name}}</li>
                            {% endfor %}
                        </ul>
                        <div class="mt-5">
                            <small class="text-muted mt-5">I agree to the processing of personal data provided in this document for realising the recruitment process pursuant to the Personal Data Protection Act of 10 May 2018 (Journal of Laws 2018, item 1000) and in agreement with Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation).</small>
                        </div>


                    </div>
                </div>


                <div class="col-3 mt-5 ms-5">
                    {% if resume.personal.photo %}
                        <img src="{{ resume.personal.photo.url }}" class='img-fluids p-0 mx-auto d-block w-100'>
                    {% endif %}
                    <p class='text-uppercase fs-3 fw-bolder text-dark mt-4'>CONTACT ME AT:</p>
                    <p class='text-dark'>Email: {{ resume.personal.email }}</p>
                    <p class='text-dark'>Phone: {{ resume.personal.phone }}</p>
                    <p class='text-dark'>Linkedin: {{ resume.personal.lin }}</p>

                    {% load custom_tags %}

                    <p class='text-uppercase fs-3 fw-bolder text-dark mt-4'>Skills</p>
                    <ul class='text-dark skills'>
                        {% for skill in resume.skill.all %}
                            <li>
                                <div class="row m-2">
                                    <div class="col-5">
                                        {{skill.name}}
                                    </div>
                                    <div class="col-7" style="margin-top: auto; margin-bottom: auto">
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-striped bg-dark" role="progressbar" style="width: {{ skill.level|skill_percents }}%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>




                </div>
            </div>
        </div>

    </body>
</html>

resumes/templates/resumes/resume_2.html
{% load static %}
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/bootstrap.css' %}"
/>
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/resume_1_2.min.css' %}"
/>
<script src="{% static 'js/bootstrap.js' %}"></script>

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Resume 2</title>
        <style type="text/css">
            ul.skills {
                list-style-type: none;
                padding-left: 0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-4 bg-primary bg-gradient p-0 me-2">
                    {% if resume.personal.photo %}
                        <img src="{{ resume.personal.photo.url }}" class='img-fluids p-0 mx-auto d-block w-100'>
                    {% endif %}
                    <br>
                    <div class="p-4">
                        <p class='text-uppercase fs-1 fw-bolder text-info mb-4'>{{ resume.personal.first_name }} {{ resume.personal.last_name }}</p>

                        <p class='text-uppercase fs-3 fw-bolder text-info  mt-4'>Career overview</p>
                        <p class='text-light'>{{ resume.personal.description }}</p>

                        {% load custom_tags %}

                        <p class='text-uppercase fs-3 fw-bolder text-info mt-4'>Skills</p>
                        <ul class='text-light skills'>
                            {% for skill in resume.skill.all %}
                                <li>
                                    <div class="row m-2">
                                        <div class="col-5">
                                            {{skill.name}}
                                        </div>
                                        <div class="col-7" style="margin-top: auto; margin-bottom: auto">
                                            <div class="progress">
                                                <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: {{ skill.level|skill_percents }}%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>

                        <p class='text-uppercase fs-3 fw-bolder text-info mt-4'>CONTACT ME AT:</p>
                        <p class='text-light'>Email: {{ resume.personal.email }}</p>
                        <p class='text-light'>Phone: {{ resume.personal.phone }}</p>
                        <p class='text-light'>Linkedin: {{ resume.personal.lin }}</p>
                    </div>
                </div>


                <div class="col-7 bg-light bg-gradient mt-5 ms-5">
                    <div class="row bg-primary bg-gradient mt-5 mb-2">
                        <p class='text-uppercase fs-3 fw-bolder text-info'>Work experience</p>
                    </div>
                    {% for exp in resume.experience.all %}
                        <p class='fs-4 fw-bolder text-info'>{{ exp.position }}</p>
                        <p class='fs-5 text-info'>{{ exp.company }} - {{ exp.city }} | {{ exp.start_date }} - {{ exp.end_date }}</p>
                        <ul class='text-dark'>
                            {% for exp_description in exp.experience_description.all %}
                                <li>{{ exp_description.description }}</li>
                            {% endfor %}
                        </ul>
                    {% endfor %}

                    <div class="row bg-primary bg-gradient mt-5 mb-2">
                        <p class='text-uppercase fs-3 fw-bolder text-info'>Education</p>
                    </div>
                    {% for school in resume.school.all %}
                        <p class='fs-4 fw-bolder text-info'>{{ school.name }} - {{ school.city }}</p>
                        <p class='fs-5 text-info'>{{ school.degree }} | {{ school.start_date }} - {{ school.end_date }}</p>
                        <ul class='text-dark'>
                            <li>Masters in Software Engineering</li>
                            <li>Took advanced courses on software architecture and computer science research</li>
                            <li>Participated in enterprise system projects</li>
                        </ul>
                    {% endfor %}

                    <div class="row bg-primary bg-gradient mt-5 mb-2">
                        <p class='text-uppercase fs-3 fw-bolder text-info'>Hobby</p>
                    </div>
                    <ul class='text-dark'>
                        {% for hobby in resume.hobby.all %}
                            <li>{{hobby.name}}</li>
                        {% endfor %}
                    </ul>
                    <div class="mt-5">
                        <small class="text-muted mt-5">I agree to the processing of personal data provided in this document for realising the recruitment process pursuant to the Personal Data Protection Act of 10 May 2018 (Journal of Laws 2018, item 1000) and in agreement with Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation).</small>
                    </div>
                </div>
            </div>
        </div>

    </body>
</html>

resumes/templates/resumes/resume_3.html
{% load static %}
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/bootstrap.css' %}"
/>
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/resume_3.min.css' %}"
/>
<script src="{% static 'js/bootstrap.js' %}"></script>

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Resume 3</title>
        <style type="text/css">
            ul.skills {
                list-style-type: none;
                padding-left: 0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-11 me-2 h-25 d-inline-block bg-dark mx-5">
                    <p class='text-uppercase fw-lighter text-primary m-5 text-center align-middle' style="font-size:70px">{{ resume.personal.first_name }} {{ resume.personal.last_name }}</p>
                </div>
                <div class="col-4 ms-5 bg-secondary">
                    <div class="p-4">
                        <p class='text-uppercase fs-3 fw-light text-dark mt-4'>Career overview</p>
                        <p class='text-dark'>{{ resume.personal.description }}</p>

                        <p class='text-uppercase fs-3 fw-light text-dark mt-4'>CONTACT ME AT:</p>
                        <p class='text-dark'>Email: {{ resume.personal.email }}</p>
                        <p class='text-dark'>Phone: {{ resume.personal.phone }}</p>
                        <p class='text-dark'>Linkedin: {{ resume.personal.lin }}</p>

                        {% load custom_tags %}

                        <p class='text-uppercase fs-3 fw-light text-dark mt-4'>Skills</p>
                        <ul class='text-dark skills'>
                            {% for skill in resume.skill.all %}
                                <li>
                                    <div class="row m-2">
                                        <div class="col-5">
                                            {{skill.name}}
                                        </div>
                                        <div class="col-7" style="margin-top: auto; margin-bottom: auto">
                                            <div class="progress">
                                                <div class="progress-bar progress-bar-striped bg-dark" role="progressbar" style="width: {{ skill.level|skill_percents }}%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>

                    </div>
                </div>


                <div class="col-7 ps-4">

                    <div class="row mt-5 mb-2">
                        <p class='text-uppercase fs-3 fw-light text-dark'>Work experience</p>
                    </div>
                    {% for exp in resume.experience.all %}
                        <p class='fs-5 fw-bolder text-dark'>{{ exp.position }}</p>
                        <p class='fs-6 text-dark fst-italic'>{{ exp.company }} - {{ exp.city }} | {{ exp.start_date }} - {{ exp.end_date }}</p>
                        <ul class='text-dark'>
                            {% for exp_description in exp.experience_description.all %}
                                <li>{{ exp_description.description }}</li>
                            {% endfor %}
                        </ul>
                    {% endfor %}

                    <div class="row mt-5 mb-3">
                        <p class='text-uppercase fs-3 fw-light text-dark'>Education</p>
                    </div>
                    {% for school in resume.school.all %}
                        <p class='fs-5 fw-bolder text-dark'>{{ school.name }} - {{ school.city }}</p>
                        <p class='fs-6 text-dark fst-italic'>{{ school.degree }} | {{ school.start_date }} - {{ school.end_date }}</p>
                        <ul class='text-dark'>
                            <li>Masters in Software Engineering</li>
                            <li>Took advanced courses on software architecture and computer science research</li>
                            <li>Participated in enterprise system projects</li>
                        </ul>
                    {% endfor %}

                    <div class="row mt-5 mb-2">
                        <p class='text-uppercase fs-3 fw-light text-dark'>Hobby</p>
                    </div>
                    <ul class='text-dark'>
                        {% for hobby in resume.hobby.all %}
                            <li>{{hobby.name}}</li>
                        {% endfor %}
                    </ul>
                    <div class="mt-5">
                        <small class="text-muted mt-5">I agree to the processing of personal data provided in this document for realising the recruitment process pursuant to the Personal Data Protection Act of 10 May 2018 (Journal of Laws 2018, item 1000) and in agreement with Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation).</small>
                    </div>

                </div>
            </div>
        </div>

    </body>
</html>

resumes/templates/resumes/resume_delete.html
{% extends 'base.html' %}

{% block title %}Delete resume {{ resume.id }}{% endblock %}

{% block content %}
    <div class="col-md-8 offset-md-2 my-4">
        <a href="{% url 'resumes:resumes' %}"><i class="bi bi-arrow-left-circle mt-4"></i></a>
        <form method="POST" class="form-group col-md-7 mt-4" id="form-container">
            {% csrf_token %}
            <h5 class="mb-4">Are you sure you want to delete "{{ resume }}" resume?</h5>
            <button type="submit" name="save" class="btn btn-danger">Delete</button>
        </form>
    </div>

{% endblock %}

resumes/templates/resumes/resume_form.html
{% extends 'base.html' %}

{% block title %}Create resume{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h2 class="text-center">CREATE RESUME</h2>

    <div class="progress my-4">
        <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 16.7%" aria-valuenow="16.7" aria-valuemin="0" aria-valuemax="100"></div>
    </div>

    <form method="POST" class="form-group" id="form-container">
        {% csrf_token %}
        <div class="d-flex justify-content-center">
            {{form|crispy}}
        </div>
        <button type="submit" name="save" class="btn btn-success float-end">Submit</button>
    </form>

{% endblock %}

resumes/templates/resumes/resume_list.html
{% extends 'base.html' %}

{% block title %}Resume list{% endblock %}

{% block content %}
    <h1 class="fw-bold text-center text-uppercase my-5">Resume List</h1>
    <div class="d-grid">
        <button type="button" class="btn btn-success btn-lg my-3"><a href='{% url "resumes:create_resume" %}'
            style="font-size:30px;"><i class="bi bi-plus align-middle" style="font-size:40px;"></i>Create resume</a></button>
    </div>
    <div class="row row-cols-1 row-cols-md-2 g-5 my-2">
        {% for resume in object_list %}
            <div class="col">
                <div class="card bg-primary mb-3 text-white bg-primary text-center" style="max-width: 50rem;">
                    <div class="card-body">
                        <h4 class="card-title"><a href='{% url "resumes:resume" resume.id %}' >
                            {% if resume.personal %}
                                {{ resume.personal }}
                            {% else %}
                                {{ resume.template }}
                            {% endif %}
                        </a></h4>
                    </div>
                    <div class="card-footer border-light">
                        <a href='{% url "resumes:update_resume" resume.id %}' class="badge rounded-pill bg-light m-1" style="font-size:15px"><i class="fas fa-list-alt" style="font-size:15px">TEMPLATE</i></a>
                        {% if resume.personal %}
                            <a href='{% url "personals:update_personal" resume.id %}' class="badge rounded-pill bg-light m-1" style="font-size:15px"><i class="fas fa-portrait" style="font-size:15px">PERSONAL</i></a>
                        {% endif %}
                        {% if resume.school.count > 0 %}
                            <a href='{% url "schools:update_school" resume.id %}' class="badge rounded-pill bg-light m-1" style="font-size:15px"><i class="fas fa-graduation-cap " style="font-size:15px">SCHOOL</i></a>
                        {% endif %}
                        {% if resume.experience.count > 0 %}
                            <a href='{% url "experiences:update_experience" resume.id %}' class="badge rounded-pill bg-light m-1" style="font-size:15px"><i class="fas fa-building" style="font-size:15px">EXPERIENCE</i></a>
                        {% endif %}
                        {% if resume.hobby.count > 0 %}
                            <a href='{% url "hobby:update_hobby" resume.id %}' class="badge rounded-pill bg-light m-1" style="font-size:15px"><i class="fas fa-gamepad" style="font-size:15px">HOBBY</i></a>
                        {% endif %}
                        {% if resume.skill.count > 0 %}
                            <a href='{% url "skills:update_skill" resume.id %}' class="badge rounded-pill bg-light m-1" style="font-size:15px"><i class="fas fa-brain" style="font-size:15px">SKILL</i></a>
                        {% endif %}
                        <a href='{% url "resumes:delete_resume" resume.id %}' class="badge rounded-pill bg-danger m-1"><i class="bi bi-x-circle-fill" style="font-size:15px">DELETE</i></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% include 'pagination.html' %}
{% endblock %}

resumes/templates/resumes/resume_update.html
{% extends 'base.html' %}

{% block title %}Update resume template{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <h2 class="text-center">UPDATE RESUME TEMPLATE</h2>

    <form method="POST" class="form-group" id="form-container">
        {% csrf_token %}
        <div class="d-flex justify-content-center">
            {{form|crispy}}
        </div>
        <button type="submit" name="save" class="btn btn-success float-end">Update</button>
    </form>

{% endblock %}